# Generated by Django 6.0 on 2025-12-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz_h',
            name='product',
        ),
        migrations.RemoveField(
            model_name='zakaz_h',
            name='mijoz',
        ),
        migrations.RenameModel(
            old_name='product_images_h',
            new_name='ProductImage',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catygory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.catygory')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.profile_c')),
                ('hunarmand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.profile_h')),
                ('mijoz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.profile_m')),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product'),
        ),
        migrations.CreateModel(
            name='Product_col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_col_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_col', to='app.profile_c')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_col', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_col_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_col_images/')),
                ('product_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product_col')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='zakaz_images/')),
                ('status', models.CharField(choices=[('tayyorlanmoqda', 'Tayyorlanmoqda'), ("yo'lda", "Yo'lda"), ('yetkazib berildi', 'Yetkazib berildi'), ('bekor qilindi', 'Bekor qilindi')], default='tayyorlanmoqda', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakaz', to='app.profile_m')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakaz', to='app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='products_h',
        ),
        migrations.DeleteModel(
            name='zakaz_h',
        ),
    ]
